# Generated by Django 4.2.5 on 2023-09-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='phone',
        ),
    ]
